project:
  type: website
  output-dir: docs
  
website:
  title: "Nivan Vora's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



